language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
before_install:
  - yarn checkup
install:
  - yarn
script:
  - yarn test --ci --coverage
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
