language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
before_install:
  - yarn checkup
install:
  - yarn
script:
  - yarn build
  - yarn test --ci --coverage
  - bash <(curl -s https://codecov.io/bash)
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then npm run chromatic; fi
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
