backend:
  name: github
  repo: agenciaglobal/web

media_folder: content/assets
public_folder: assets

collections:
  - name: news
    label: Notícias
    folder: content/news
    create: true
    fields:
      - { name: path, label: Path }
      - name: type
        label: Tipo do box de exibição na lista
        widget: select
        options:
          - { label: "Full", value: "FULL" }
          - { label: "Half", value: "HALF" }
          - { label: "Mirror", value: "MIRROR" }
          - { label: "Left", value: "LEFT" }
          - { label: "Right", value: "RIGHT" }
          - { label: "Quote", value: "QUOTE" }
      - { name: date, label: Data, widget: date }
      - name: postType
        label: Tipo de post
        widget: select
        options:
          - { label: "Notícia", value: "news" }
          - { label: "Artigo", value: "article" }
      - { name: title, label: Título }
      - { name: description, label: Descrição }
      - name: "image"
        label: "Imagem de destaque"
        widget: "image"
        default: "/content/assets/uma.png"
      - { name: "body", label: "Conteúdo do blog post", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        multiple: true
        searchFields: ["tag"]
        valueField: "tag"
        displayFields: ["tag"]
      - label: "Autor do post"
        name: "author"
        widget: "relation"
        collection: "team"
        searchFields: ["name", "about", "image"]
        valueField: "name"
        displayFields: ["name"]
  - name: tags
    label: Tags
    folder: content/tags
    create: true
    fields:
      - { name: tag, label: tag, widget: string }
  - name: client
    label: Clientes
    folder: content/client
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Cliente }
      - label: "Logo"
        name: "image"
        widget: "image"
        default: "/content/assets/uma.png"
        media_library:
          config:
            multiple: true
      - { name: testimonial, label: Depoimento }
      - { name: author, label: Autor }
      - label: "Foto do autor"
        name: "author_image"
        widget: "image"
        default: "/content/assets/uma.png"
        media_library:
          config:
            multiple: true
  - name: portifolio
    label: Portifolio
    folder: content/portifolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: creation date, label: Data publicação, widget: date }
      - { name: job date, label: Data do job, widget: date }
      - { name: title, label: Title }
      - { name: text_1, label: "Text Principal" }
      - { name: text_2, label: "Text Secundário" }
      - { name: text_3, label: "Terceiro Text" }
      - { name: text_4, label: "Quarto Text" }
      - { name: youtube, label: "Youtube ID" }
      - { name: description, label: Description }
      - label: "Autor do post"
        name: "author"
        widget: "relation"
        collection: "team"
        searchFields: ["name", "about", "image"]
        valueField: "name"
        displayFields: ["name"]
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/content/assets/uma.png"
      - label: "Image 1"
        name: "image_1"
        widget: "image"
        default: "/content/assets/uma.png"
      - label: "Image 2"
        name: "image_2"
        widget: "image"
        default: "/content/assets/uma.png"
      - label: "Image 3"
        name: "image_3"
        widget: "image"
        default: "/content/assets/uma.png"
      - name: categorie
        label: Categorie
        widget: select
        options:
          - { label: "featured", value: "featured" }
          - { label: "digital", value: "digital" }
          - { label: "social", value: "social" }
          - { label: "crm", value: "crm" }
          - { label: "advertising", value: "advertising" }
  - name: team
    label: Team
    folder: content/team
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Nome }
      - { name: job, label: Cargo }
      - { name: about, label: Sobre }
      - label: "Foto P&B"
        name: "black_image"
        widget: "image"
        default: "/content/assets/uma.png"
        media_library:
          config:
            multiple: true
      - label: "Foto colorida"
        name: "image"
        widget: "image"
        default: "/content/assets/uma.png"
        media_library:
          config:
            multiple: true
